# Generated by Django 5.0.3 on 2024-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=500, verbose_name='Unidad')),
                ('estauno', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estados', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estatres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estacuatro', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estacinco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estaseis', models.DecimalField(decimal_places=2, max_digits=9)),
                ('estasiete', models.DecimalField(decimal_places=2, max_digits=9)),
                ('demerito', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pruebac', models.DecimalField(decimal_places=2, max_digits=9)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
