# Generated by Django 5.0.3 on 2024-03-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
