# Generated by Django 5.0.3 on 2024-03-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_codigo_morse_criptografía_mensajero_mtrr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptografía',
            name='cifrado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='decifrado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='medidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='metodos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='principios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
