# Generated by Django 5.0.3 on 2024-03-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_resultados_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
