# Generated by Django 5.0.3 on 2024-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0003_alter_criptografía_cifrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criptografía',
            name='divido',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='criptografía',
            name='resultado',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
