# Generated by Django 5.0.3 on 2024-03-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0004_alter_criptografía_divido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='red_hf',
            old_name='conectividad',
            new_name='expedienteOT',
        ),
    ]
