# Generated by Django 5.0.3 on 2024-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0005_rename_conectividad_red_hf_expedienteot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='red_hf',
            name='divido',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='red_hf',
            name='resultado',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
