# Generated by Django 5.0.3 on 2024-03-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0006_alter_red_hf_divido_alter_red_hf_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red_vhf',
            name='uno',
        ),
        migrations.AddField(
            model_name='red_vhf',
            name='uno',
            field=models.ManyToManyField(to='votos.resultados'),
        ),
    ]
