# Generated by Django 5.0.3 on 2024-03-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0007_remove_red_vhf_uno_red_vhf_uno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criptografía',
            new_name='Criptografia',
        ),
    ]
