# Generated by Django 5.0.3 on 2024-03-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0008_rename_criptografía_criptografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codigo_morse',
            old_name='suma',
            new_name='suma6',
        ),
        migrations.RenameField(
            model_name='criptografia',
            old_name='suma',
            new_name='suma2',
        ),
        migrations.RenameField(
            model_name='mensajero',
            old_name='suma',
            new_name='suma4',
        ),
        migrations.RenameField(
            model_name='mtrr',
            old_name='suma',
            new_name='suma5',
        ),
        migrations.RenameField(
            model_name='radioaficionados',
            old_name='suma',
            new_name='suma7',
        ),
        migrations.RenameField(
            model_name='red_hf',
            old_name='suma',
            new_name='suma3',
        ),
        migrations.RenameField(
            model_name='red_vhf',
            old_name='suma',
            new_name='suma1',
        ),
    ]
